server:
    port: 8080
    tomcat: 
      uri-encoding: UTF-8
      max-threads: 100
      min-spare-threads: 10
      protocol-header: X-Forwarded-Proto

logPath: ./logs

logging: 
    file: <#noparse>${logPath}</#noparse>/${appname}.log
    level.org.hibernate.SQL: DEBUG
    level.${basepackage}: DEBUG

spring.jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate.ddl-auto: none

${appname}: 
    dburl: 127.0.0.1:3306/${appname}
    dbuser: root
    dbpwd: 123456

spring.datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<#noparse>${</#noparse>${appname}.dburl}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
    username: <#noparse>${</#noparse>${appname}.dbuser}
    password: <#noparse>${</#noparse>${appname}.dbpwd}
    poolName: SpringBootHikariCP
    maximumPoolSize: 20
    minimumIdle: 3
#    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 250
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
#spring.jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
<#noparse>
redis.host: 100.216.0.12
redis.pwd:
redis.port: 6379 

spring.redis: 
    database: 0
    host: ${redis.host}
    password: ${redis.pwd}
    port: ${redis.port}
    expires:  #非标准参数，自定义的，子元素为缓存名：缓存有效期（单位秒）
        SessionCache: 43200

returnValue.autoWrapper: #设置各请求方式返回值是否自动包装
    post: true
    put: true
    delete: true
    get: true
</#noparse>
mybatis: 
    mapperLocations: /mapper/**/*.xml